from jinxicon import jinxicon_rcc


ICON_ASSET_LRG = ":/jinxicon/img/ICON_ASSET_LRG.png"
ICON_ASSET_MED = ":/jinxicon/img/ICON_ASSET_MED.png"
ICON_ASSET_SML = ":/jinxicon/img/ICON_ASSET_SML.png"
ICON_FILTER_LRG = ":/jinxicon/img/ICON_FILTER_LRG.png"
ICON_FILTER_MED = ":/jinxicon/img/ICON_FILTER_MED.png"
ICON_FILTER_SML = ":/jinxicon/img/ICON_FILTER_SML.png"
ICON_FOLDER_LRG = ":/jinxicon/img/ICON_FOLDER_LRG.png"
ICON_FOLDER_MED = ":/jinxicon/img/ICON_FOLDER_MED.png"
ICON_FOLDER_SML = ":/jinxicon/img/ICON_FOLDER_SML.png"
ICON_JOB_LRG = ":/jinxicon/img/ICON_JOB_LRG.png"
ICON_JOB_MED = ":/jinxicon/img/ICON_JOB_MED.png"
ICON_JOB_SML = ":/jinxicon/img/ICON_JOB_SML.png"
ICON_PLUS_LRG = ":/jinxicon/img/ICON_PLUS_LRG.png"
ICON_PLUS_MED = ":/jinxicon/img/ICON_PLUS_MED.png"
ICON_PLUS_SML = ":/jinxicon/img/ICON_PLUS_SML.png"
ICON_RELOAD_LRG = ":/jinxicon/img/ICON_RELOAD_LRG.png"
ICON_RELOAD_MED = ":/jinxicon/img/ICON_RELOAD_MED.png"
ICON_RELOAD_SML = ":/jinxicon/img/ICON_RELOAD_SML.png"
ICON_SCROLL_LRG = ":/jinxicon/img/ICON_SCROLL_LRG.png"
ICON_SCROLL_MED = ":/jinxicon/img/ICON_SCROLL_MED.png"
ICON_SCROLL_SML = ":/jinxicon/img/ICON_SCROLL_SML.png"
ICON_SEARCH_LRG = ":/jinxicon/img/ICON_SEARCH_LRG.png"
ICON_SEARCH_MED = ":/jinxicon/img/ICON_SEARCH_MED.png"
ICON_SEARCH_SML = ":/jinxicon/img/ICON_SEARCH_SML.png"
ICON_SEQUENCE_LRG = ":/jinxicon/img/ICON_SEQUENCE_LRG.png"
ICON_SEQUENCE_MED = ":/jinxicon/img/ICON_SEQUENCE_MED.png"
ICON_SEQUENCE_SML = ":/jinxicon/img/ICON_SEQUENCE_SML.png"
ICON_SHOT_LRG = ":/jinxicon/img/ICON_SHOT_LRG.png"
ICON_SHOT_MED = ":/jinxicon/img/ICON_SHOT_MED.png"
ICON_SHOT_SML = ":/jinxicon/img/ICON_SHOT_SML.png"
ICON_SLIDERS_LRG = ":/jinxicon/img/ICON_SLIDERS_LRG.png"
ICON_SLIDERS_MED = ":/jinxicon/img/ICON_SLIDERS_MED.png"
ICON_SLIDERS_SML = ":/jinxicon/img/ICON_SLIDERS_SML.png"
